---
# tasks file for ansible-role-systemd-nspawn
- name: ensure that systemd_nspawn_machines contains machine names
  assert:
    that: systemd_nspawn_machines is iterable
  tags:
    - always

- name: Run pacstrap
  include: pacstrap.yml
  tags:
    - pacstrap
    - systemd_nspawn.pacstrap

- name: include template tasks
  include: template.yml
  tags:
    - template
    - systemd_nspawn.template

- name: include service tasks
  include: service.yml
  tags:
    - service
    - systemd_nspawn.service

- name: include name service switch tasks
  include: nsswitch.yml
  tags:
    - nsswitch
    - name_service
    - systemd_nspawn.nsswitch
    - systemd_nspawn.name_service
